apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: prometheus
  app.kubernetes.io/part-of: ingress-nginx
resources:
- prometheus-role.yaml
- prometheus-service-account.yaml
- prometheus-role-binding.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
- prometheus-ingress.yaml
images:
- name: prom/prometheus
  newTag: v2.13.1
configMapGenerator:
- name: prometheus-configuration
  files:
  - prometheus.yaml
