apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer" # <--- Comment this line out if you're not using cert-manager
    nginx.ingress.kubernetes.io/auth-type: basic # <--- Comment out if you are not using basic auth
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth # <--- Comment out if you are not using basic auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Login' # <--- Comment out if you are not using basic auth
spec:
  tls:
  - hosts:
    - prom.ostrike.com
    secretName: promcert # <--- Comment this line out if you're not using cert-manager
  rules:
  - host: prom.ostrike.com
    http:
      paths:
      - backend:
          serviceName: prometheus-server-service
          servicePort: 9090
