apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: ingress-nginx
resources:
- grafana-stateful-set.yaml
- grafana-config-map.yaml
- grafana-dashboards-config-map.yaml
- grafana-service.yaml
- grafana-ingress.yaml
images:
- name: grafana/grafana
  newTag: 6.3.6 #6.1.6
