apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vrpoc-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod       # change this value
spec:
  tls:
  - hosts:
    - vrpoc.litpoc.com
    secretName: letsencrypt-prod                              # change this value
  rules:
  - host: vrpoc.litpoc.com
    http:
      paths:
      - backend:
          serviceName: vrpoc-service
          servicePort: 80
