apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pod-node-admin-rbac
  namespace: default
subjects:
- kind: ServiceAccount
  name: cluster-pod-node-reader
roleRef:
  kind: ClusterRole
  name: pod-node-admin
  apiGroup: rbac.authorization.k8s.io
